### verify token
GET https://us-central1-testapi-d3e3a.cloudfunctions.net/login/verify-token/<token>

### verify code
PUT https://us-central1-testapi-d3e3a.cloudfunctions.net/admin/verify-code/468993
Authorization: Bearer <token>

### send-verify-email
PUT https://us-central1-testapi-d3e3a.cloudfunctions.net/admin/send-verify-gmail
Authorization: Bearer <token>

### sign in admin
GET https://us-central1-testapi-d3e3a.cloudfunctions.net/login/sign-in-admin/<username>-<password>

### sign in user
GET https://us-central1-testapi-d3e3a.cloudfunctions.net/login/sign-in/<username>-<password>

### get current version of map
GET https://us-central1-testapi-d3e3a.cloudfunctions.net/getLevelMap/get-current-version-of-map
Authorization: Bearer <token>

### add map
POST https://us-central1-testapi-d3e3a.cloudfunctions.net/editLevelMap/add-map
Authorization: Bearer <token>
